name: p_lets_talk
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_auth: ^3.9.0
  firebase_core: ^1.22.0
  cloud_firestore: ^3.4.8
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

